package com.jobportal.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "job_seeker_profiles")
@Getter
@Setter
@NoArgsConstructor
public class JobSeekerProfile {

    @Id
    private Long id; // Primary key, same as User ID

    @OneToOne(fetch = FetchType.LAZY)
    @MapsId // This makes the 'id' field both primary key and foreign key
    @JoinColumn(name = "user_id")
    private User user;

    private String fullName;
    private String contactPhone;

    @Column(columnDefinition = "TEXT")
    private String skillsSummary;

    @Column(columnDefinition = "TEXT")
    private String education;

    @Column(columnDefinition = "TEXT")
    private String experience;

    private String resumeFilePath; // Path to the uploaded resume file

    // Constructor, getters, and setters will be generated by Lombok
    // but a constructor for user might be useful
    public JobSeekerProfile(User user) {
        this.user = user;
        if (user != null && user.getId() != null) {
            this.id = user.getId();
        }
        // Note: @NoArgsConstructor from Lombok handles the public JobSeekerProfile() {}
    }
}
